config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :patches, except: %i[destroy index]  do
    member do
      get :setup, :care, :planting, :harvesting
    end
    resources :vegetables, only: :show
  end

  resources :crops, only: :update
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crop.rb
class Crop < ApplicationRecord
  belongs_to :vegetable
  belongs_to :patch

  scope :planted, -> { where.not(planting_date: nil) }
  scope :harvested, -> { where.not(harvesting_date: nil) }

  def planted?
    !planting_date.nil?
  end

  def harvested?
    !harvesting_date.nil?
  end

  def days_until_harvest
    harvest_date = planting_date + vegetable.growing_length.days

    [harvest_date - Date.today, 0].max.to_i
  end
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :vegetable
end

app/models/patch.rb
class Patch < ApplicationRecord
  belongs_to :user
  has_many :crops
  has_many :vegetables, through: :crops
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :patches
  validates :name, presence: true
end

app/models/vegetable.rb
class Vegetable < ApplicationRecord
  SEASONS = [
    {
      name: 'Spring',
      start_month: 3,
      start_day: 20,
      end_month: 6,
      end_day: 1
    },
    {
      name: 'Summer',
      start_month: 5,
      start_day: 25,
      end_month: 9,
      end_day: 1
    },
    {
      name: 'Autumn',
      start_month: 9,
      start_day: 22,
      end_month: 12,
      end_day: 1
    },
    {
      name: 'Winter',
      start_month: 12,
      start_day: 21,
      end_month: 3,
      end_day: 1
    }
  ]

  has_many :crops
  has_one :instruction
  has_many :patches, through: :crops
  has_one_attached :photo
  validates :planting_season, inclusion: { in: SEASONS.map { |season| season[:name] }}

  def days_until_planting
    date = SEASONS.find { |season| season[:name] == planting_season }
    today = Date.today

    start_date = Date.new(today.year, date[:start_month], date[:start_day])
    end_date = Date.new(today.year, date[:end_month], date[:end_day])

    if (today >= start_date) && (today <= end_date)
      return 0
    end

    if date[:start_month] >= today.month && date[:start_day] >= today.day
      season_date = Date.new(today.year, date[:start_month], date[:start_day])
    else
      season_date = Date.new(today.year + 1, date[:start_month], date[:start_day])
    end

    [(season_date - today).to_i, 0].max
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  def update
    @crop = Crop.find(params[:id])
    @crop.update(crop_params)

    options = {}
    options[:harvested] = @crop.id if @crop.harvesting_date_previously_changed?

    redirect_to harvesting_patch_path(@crop.patch, options)
  end

  private

  def crop_params
    params.require(:crop).permit(:planting_date, :harvesting_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    # Go to the first patch when the user is logged in and has patches
    redirect_to patch_path(current_user.patches.first) if user_signed_in? && current_user.patches.present?
  end
end

app/controllers/patches_controller.rb
class PatchesController < ApplicationController
  before_action :find_patch, except: [:new, :create]

  def new
    @patch = Patch.new
  end

  def create
    @patch = Patch.new(patch_params)
    @patch.user = current_user

    if @patch.save
      redirect_to edit_patch_path(@patch)
    else
      render :new
    end
  end

  def show
    @patches = current_user.patches.find(params[:id])
  end

  def edit
    @vegetables = Vegetable.where('sun_score < ?', @patch.hours_of_sun)
  end

  def update
    @patch.update(patch_params)

    redirect_to patch_path(@patch)
  end

  def planting
    @vegetables = @patch.vegetables
  end

  def harvesting
    @crops = @patch.crops.planted
  end

  def setup
  end

  def care
  end

  private

  def patch_params
    params.require(:patch).permit(:hours_of_sun, vegetable_ids: [])
  end

  def find_patch
    @patch = Patch.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    if resource.patches.present?
      '/patches'
    else
      '/patches/new'
    end
  end
end

app/controllers/vegetables_controller.rb
class VegetablesController < ApplicationController
  def show
    @patch = Patch.find(params[:patch_id])
    @vegetable = Vegetable.find(params[:id])
    @instruction = @vegetable.instruction
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patched</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <!-- <div class="body-wrapper"> -->
      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/patches/care.html.erb
<div class="body-wrapper">
<div>
  <div class="background pt-3">
    <div class="pages-container">
     <h1>Care for your patch</h1>
     </div>
     <div>
      <ul class="nav nav-pills mb-3 list-inline tabs-underlined active" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active tab-underlined" id="pills-watering-tab" href="#pills-watering" data-toggle="pill" role="tab" aria-controls="pills-watering" aria-selected="true">Watering</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link tab-underlined" id="pills-weeds-tab" href="#pills-weeds" data-toggle="pill" role="tab" aria-controls="pills-weeds" aria-selected="false">Weeds</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link tab-underlined" id="pills-soil-tab" href="#pills-soil" data-toggle="pill" role="tab" aria-controls="pills-soil" aria-selected="false">Soil</button>
        </li>
      </ul>
    </div>
  </div>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-watering" role="tabpanel" aria-labelledby="pills-home-tab">
      <div class="bottom-container">
        <div class="container-small-card">
          <div class="small-card-extra">
            <h6 class="header-small">Frequency</h6>
            <p class="p-big">Once a week</p>
          </div>
          <div class="small-card-extra">
            <h6 class="header-small">Amount</h6>
            <p class="p-big">2-5cm</p>
          </div>
        </div>
        <div class="steps-container">
          <div class="card-step">
            <ul class="list-ellipse-class-2">
              <li class="list-bullets-1">Water your patch with an inch or two of water per week. We recommend using a garden hose for convenience but you can also use a watering can.</li>
            </ul>
          </div>
          <div class="card-step">
            <ul class="list-ellipse-class-2">
              <li class="list-bullets-2">Aim to water the roots of the plant, not the leaves.</li>
            </ul>
          </div>
          <div class="card-step">
            <ul class="list-ellipse-class-2">
              <li class="list-bullets-3">To avoid water waste setup a rainwater collector in your garden.</li>
            </ul>
            <%= image_tag "watering.jpg", class: "watering-pic" %>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-weeds" role="tabpanel" aria-labelledby="pills-weeds-tab">
      <div class="large-card-extra-container">
        <div class="large-card-extra">
          <h6 class="header-small">Frequency</h6>
          <p class="p-big">Weed once a week</p>
        </div>
        <div>
          <div class="card-step">
            <ul class="list-ellipse-class-3">
              <li class="list-bullets-1">Manually remove weeds from your garden to avoid buildup. This will prevent you from needing to use any nasty chemicals.</li>
            </ul>
          </div>
          <div class="card-step">
            <ul class="list-ellipse-class-3">
              <li class="list-bullets-2">Pull them out gently, try to remove the whole weed, including the roots.</li>
            </ul>
          </div>
          <div class="care-card">
            <h6>What to look out for</h6>
            <p>Here are some common weeds to pull out of your patch.</p>
          </div>
          <div class="cards-container-weeds">
            <div class="card-weed">
              <%= image_tag "fat-hen-weed.jpg", class: "small-card-pic" %>
              <h6>Fat hen</h6>
            </div>
            <div class="card-weed">
              <%= image_tag "sticky-weed.jpg", class: "small-card-pic" %>
              <h6>Sticky weed</h6>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-soil" role="tabpanel" aria-labelledby="pills-soil-tab">
      <div class="bottom-container">
        <div class="container-small-card">
          <div class="small-card-extra">
            <h6 class="header-small">Frequency</h6>
            <p class="p-big">Once a year</p>
          </div>
          <div class="small-card-extra">
            <h6 class="header-small">Layer depth</h6>
            <p class="p-big">5cm</p>
          </div>
        </div>
        <div class="card-step">
          <ul class="list-ellipse-class-2">
            <li class="list-bullets-1">Spread a 5cm layer of organic mulch over your patch once or twice a year, to keep your soil rich and to keep weeds and pests at bay. It will also reduce water evaporation.</li>
          </ul>
        </div>
        <div class="care-card-2">
          <h6>Organic mulches</h6>
          <p>Here are some mulches we recommend for your patch.</p>
        </div>
        <div class="cards-container-weeds">
          <div class="card-weed-2">
            <%= image_tag "hay.jpg", class: "small-card-pic" %>
            <h6>Hay or straw</h6>
          </div>
          <div class="card-weed-2">
            <%= image_tag "woodchip.jpg", class: "small-card-pic" %>
            <h6>Woodchip</h6>
          </div>
          <div class="card-weed-2">
            <%= image_tag "leaves.jpg", class: "small-card-pic" %>
            <h6>Leaves</h6>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render 'shared/menu' %>
</div>
</div>

app/views/patches/edit.html.erb
<div class="body-wrapper">
<div class="background">
  <div class="pages-container">
    <%= link_to new_patch_path do %>
      <%= image_tag "button/backarrow.png", class:"buttonarrow-left" %>
    <% end %>

    <h1>Your vegetable selection</h1>
    <p>These vegetables perfectly match your garden.</p>
    <p>Select the vegetables you would like to grow in your patch.</p>
    <h5>Select up to 5</h5>

    <%= simple_form_for @patch do |f| %>
      <%= f.association :vegetables,
        as: :check_boxes,
        collection: @vegetables,
        legend_tag: false,
        item_wrapper_class: 'd-none' %>

      <% @vegetables.each do |vegetable| %>
        <a href="#" class="vegetable-card js-vegetable-item mb-3" data-target="patch_vegetable_ids_<%= vegetable.id %>">
          <%= cl_image_tag vegetable.photo.key, width: 45, height: 45, crop: :fill, class: 'vegetable-photo' %>
          <span class="flex-grow-1 ml-3 font-size-h5"><%= vegetable.name %></span>
          <div class="check">
            <svg class="tick" width="18" height="15" viewBox="0 0 18 15" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M1.5 7.66667L6.5 13L16.5 1" stroke="white" stroke-width="2"/>
            </svg>
          </div>
        </a>
      <% end %>

      <div class="action">
        <%= f.submit 'Confirm', class: 'gen-text' %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/patches/harvesting.html.erb
<div class="body-wrapper">
<div class="background pt-3">
  <div class="pages-container">
      <h1>Harvesting</h1>
  </div>
  <ul class="nav nav-pills mb-3 list-inline tabs-underlined active" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active tab-underlined" id="pills-home-tab" href="#pills-home" data-toggle="pill" role="tab" aria-controls="pills-home" aria-selected="true">Vegetables</button>
    </li>
  </ul>
</div>

<div class="background-light">
  <div class="harvesting-wraper mt-4 mx-4">
    <% @crops.each do |crop| %>
      <%= link_to patch_vegetable_path(@patch, crop.vegetable, instruction_type: 'harvesting'), class: 'vegetable-card-slider mb-3' do %>
        <%= cl_image_tag(crop.vegetable.photo.key, width: 58, height: 58, crop: :fill, radius: 10)%>

        <div class="vegetable-card-content">
          <h5 class="font-size-h5"><%= crop.vegetable.name %></h5>
          <% if crop.harvested? %>
            <p>Already harvested</p>
          <% elsif crop.days_until_harvest.zero? %>
            <p>Ready to harvest!</p>
          <% else %>
            <p><%= pluralize(crop.days_until_harvest, 'day') %> until harvest</p>
          <% end %>

          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: <%= 100 - (crop.days_until_harvest * 100 / crop.vegetable.growing_length) %>%; background-color: #900B63;" aria-valuenow="<%= crop.days_until_harvest %>" aria-valuemin="0" aria-valuemax="<%= crop.vegetable.growing_length %>"></div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<% if params[:harvested] %>
  <% crop = Crop.find(params[:harvested]) %>
  <div class="d-none js-harvest-popup">
    Congratulations! You harvested <%= crop.vegetable.name %>!
  </div>
<% end %>

<%= render 'shared/menu' %>
</div>

app/views/patches/new.html.erb
<div class="background">
  <div class="pages-container-taller">
    <%= link_to root_path do %>
      <%= image_tag "button/backarrow.png", class:"buttonarrow-left" %>
    <% end %>
    <div class="form-style">
      <%= simple_form_for @patch do |f| %>
        <h1>What is your location?</h1>
        <%= f.input :location, label: "Location", class:"form-control" %>
        <h1>How sunny is your garden?</h1>
        <div class="d-flex justify-content-between">
          <p class="hi">Very shady</p><p class="hi">Very sunny</p>
        </div>
        <%= f.input :hours_of_sun, collection: (1..6).to_a, label: false %>
        <%= f.button :submit, class:"btn btn-primary w-100 my-4 px-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/patches/planting.html.erb
<div class="body-wrapper">
<div class="background pt-3">
  <div class="pages-container">
    <h1>Planting</h1>
  </div>
  <ul class="nav nav-pills mb-3 list-inline tabs-underlined active" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active tab-underlined" id="pills-home-tab" href="#pills-home" data-toggle="pill" role="tab" aria-controls="pills-home" aria-selected="true">Vegetables</button>
    </li>
  </ul>
</div>

<div class="background-light">
  <div class="planting-wraper mt-4 mx-4">
    <% @vegetables.each do |vegetable| %>
      <%= link_to patch_vegetable_path(@patch, vegetable, instruction_type: 'planting'), class: 'vegetable-card-slider mb-3' do %>
        <%= cl_image_tag(vegetable.photo.key, width: 58, height: 58, crop: :fill, radius: 10) %>

        <div class="vegetable-card-content">
          <h5 class="font-size-h5"><%= vegetable.name %></h5>
          <% if vegetable.days_until_planting.zero? %>
            <p>Ready to plant!</p>
          <% else %>
            <p><%= pluralize(vegetable.days_until_planting, 'day') %> to go until planting</p>
          <% end %>
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: <%= 100 - (vegetable.days_until_planting * 100 / 365) %>%; background-color: #572271;" aria-valuenow="<%= vegetable.days_until_planting %>" aria-valuemin="0" aria-valuemax="365"></div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= render 'shared/menu' %>
</div>

app/views/patches/setup.html.erb
<div class="body-wrapper">
<div>
  <div class="background pt-3">
    <div class="pages-container">
     <h1>Set up your patch</h1>
    </div>
    <ul class="nav nav-pills mb-3 list-inline tabs-underlined active" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active tab-underlined" id="pills-home-tab" href="#pills-home" data-toggle="pill" role="tab" aria-controls="pills-home" aria-selected="true">You need</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link tab-underlined" id="pills-assembly-tab" href="#pills-assembly" data-toggle="pill" role="tab" aria-controls="pills-assembly" aria-selected="false">Assembly</button>
      </li>
    </ul>
  </div>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <div class="cards-container">
        <div class="row">
          <div class="card-setup col-6">
              <div class="card-body">
                 <%= image_tag "cardboardboxes.jpg", class: "card-img-top" %>
                <h5 class="card-text">Cardboard boxes</h5>
                <p class="card-text">10-14</p>
                <p class="card-text">Used</p>
                <h6 class="card-text">How to find</h6>
              </div>
          </div>
          <div class="card-setup col-6">
              <div class="card-body">
                <%= image_tag "raisedbedframe.jpg", class: "card-img-top" %>
                <h5 class="card-text">1 raised bed frame</h5>
                <p class="card-text">1.2m x 1.2m</p>
                <p class="card-text">Recycled wood</p>
                <h6 class="card-text">Make your own</h6>
              </div>
          </div>
          <div class="card-setup col-6">
              <div class="card-body">
                <%= image_tag "gardenshovel.jpg", class: "card-img-top" %>
                <h5 class="card-text">Garden shovel</h5>
                <p class="card-text">80cm</p>
                <p class="card-text">Recycled materials</p>
                <h6 class="card-text">Expert advise</h6>
              </div>
          </div>
          <div class="card-setup col-6">
              <div class="card-body">
                <%= image_tag "organiccompost.jpg", class: "card-img-top" %>
                <h5 class="card-text">Organic compost</h5>
                <p class="card-text">400g</p>
                <p class="card-text">Chipping-based</p>
                <h6 class="card-text">Make your own</h6>
              </div>
          </div>
          <div class="card-setup col-6">
              <div class="card-body">
                <%= image_tag "organicsoil.jpg", class: "card-img-top" %>
                <h5 class="card-text">Organic soil</h5>
                <p class="card-text">400g</p>
                <p class="card-text">Nutrient-riched</p>
                <h6 class="card-text">Make your own</h6>
              </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="pills-assembly" role="tabpanel" aria-labelledby="pills-assembly-tab">
      <div class="card-text-step">
        <ul class="list-ellipse-class">
          <li class="list-bullets-1">
            <h5>Step One</h5>
            <p>Start by laying cardboard over the area the new bed will occupy. This will help to clear all the grass and weeds beneath.</p>
          </li>
        </ul>
      </div>
      <div class="card-text-step">
        <ul class="list-ellipse-class">
          <li class="list-bullets-2">
            <h5>Step Two</h5>
            <p>After the grass has rotted down, remove the cardboard and lay out your raised bed frame where you would like your patch to be.</p>
          </li>
        </ul>
      </div>
      <div class="card-text-step">
        <ul class="list-ellipse-class">
          <li class="list-bullets-3">
            <h5>Step Three</h5>
            <p>Assemble the frame or <strong>create your own with our simple guide.</strong></p>
          </li>
        </ul>
        <%= image_tag "assempagepic.jpg", class: "assembly-pic" %>
      </div>
      <div class="card-text-step">
        <ul class="list-ellipse-class">
          <li class="list-bullets-4">
            <h5>Step Four</h5>
            <p>With the walls of the raised bed fixed together, it's time to fill it. Add organic garden compost and soil to the bed. This will introduce lots of beneficial microorganisms to the soil, which will further enhance plant growth.</p>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <%= render 'shared/menu' %>
</div>
</div>

app/views/patches/show.html.erb
<div class="body-wrapper">
<div>
<div class="background pt-3">
  <div class="pages-container">
    <h1>Welcome <%= current_user.name.capitalize %></h1>
  </div>
    <ul class="nav nav-pills mb-3 list-inline tabs-underlined active" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active tab-underlined" id="pills-patches-tab" href="#pills-patches" data-toggle="pill" role="tab" aria-controls="pills-patches" aria-selected="true">My patches</button>
      </li>
    </ul>
  </div>

<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-patches" role="tabpanel" aria-labelledby="pills-patches-tab">
      <div class="background-light">
        <div class="pages-container">
          <div class="med-image title" style="background-image: url(<%= cl_image_path('https://res.cloudinary.com/dmixbgvgw/image/upload/v1623240571/Patched/mypatch.jpg')%>">
            <%= link_to edit_patch_path(@patch) do %>
              <button class="edit-btn">Edit</button>
            <% end %>
            <div class="title-box">
              <p class="patch-name">My patch</p>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
</div>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-notifications" role="tabpanel" aria-labelledby="pills-notifications-tab">
      <div class="background-light">
        <div class="pages-container">
        </div>
      </div>
    </div>
  </div>

<%= render 'shared/menu' %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Patched</a>
  <button class="navbar-toggler pr-0" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon">
    </span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/vegetables/_harvesting_check_box.html.erb
<% if crop.present? && crop.days_until_harvest.zero? %>
  <%= simple_form_for crop do |f| %>
    <%= f.input :harvesting_date, label: false, input_html: { class: 'd-none' } %>
    <%= check_box_tag :harvested, 1, crop.harvested?, class: 'd-none', id: 'planted_check' %>

    <%= link_to harvesting_patch_path(@patch), class: 'vegetable-card-checkbox-harvesting mx-3 mb-3 js-crop-check', data: { submit: "edit_crop_#{crop.id}" } do %>
      <span class="flex-grow-1 ml-3 font-size-h5">
        <svg class="harvesting-icon" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M16 8C16 12.4183 12.4183 16 8 16C3.58172 16 0 12.4183 0 8C0 3.58172 3.58172 0 8 0C12.4183 0 16 3.58172 16 8Z" fill="white"/>
          <path fill-rule="evenodd" clip-rule="evenodd" d="M7.99992 1.43262L8.23603 1.55911C10.6787 2.86768 11.835 5.33062 12.2768 6.74969C12.4769 7.39212 12.4426 8.07317 12.2167 8.69001C11.1744 11.5363 9.19405 12.4998 7.99992 12.4998H7.94122L7.88411 12.4862C6.40231 12.1334 5.39525 11.5 4.72167 10.7378C4.051 9.97896 3.74128 9.12699 3.59455 8.38421C3.50465 7.92909 3.52417 7.45615 3.65895 7.00776C4.01825 5.81251 4.75029 4.61445 5.51898 3.64865C6.2802 2.69222 7.12895 1.89921 7.76381 1.55911L7.99992 1.43262ZM6.30141 4.27138C5.57957 5.17833 4.92687 6.26353 4.61662 7.29564C4.53003 7.58369 4.51647 7.89111 4.57559 8.19041C4.69884 8.81431 4.94999 9.4861 5.47098 10.0756C5.98096 10.6526 6.77902 11.1844 8.05461 11.4986C8.78491 11.467 10.3765 10.8071 11.2777 8.34614C11.4337 7.92026 11.4522 7.46479 11.3221 7.047C10.9297 5.78703 9.95193 3.73977 8.01004 2.57998C7.55304 2.89345 6.92065 3.49335 6.30141 4.27138Z" fill="#910B63"/>
          <path fill-rule="evenodd" clip-rule="evenodd" d="M7.5 14.5V7H8.5V14.5H7.5Z" fill="#910B63"/>
        </svg>
        <%= crop.vegetable.name %> is harvested?</span>
      <div class="check">
        <svg class="tick" width="18" height="15" viewBox="0 0 18 15" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M1.5 7.66667L6.5 13L16.5 1" stroke="white" stroke-width="2"/>
        </svg>
      </div>
    <% end %>
  <% end %>
<% end %>